<<<<<<< HEAD
name: Build, Push, and Deploy Docker Image to AWS EC2
=======
name: Build, Push and Deploy Docker Image
>>>>>>> ba5e9c25f5398895d769d2d65887f12f1932f92c

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    outputs:
      image-tag: mrizqiis/simple-app:0.1.0

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mrizqiis/simple-app
          tags: |
            type=raw,value=0.1.0

      - name: Build and Push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

<<<<<<< HEAD
      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull mrizqiis/simple-app:0.1.0
            docker stop web-app || true
            docker rm web-app || true
            docker run -d --name web-app -p 80:80 mrizqiis/simple-app:0.1.0
=======
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull mrizqiis/simple-app:0.1.0
            docker stop simple-app || true
            docker rm simple-app || true
            docker run -d --name simple-app -p 80:80 mrizqiis/simple-app:0.1.0
>>>>>>> ba5e9c25f5398895d769d2d65887f12f1932f92c
